// Alternate names lifters actually type, mapped to our canonical exercise
// names, so search finds "skull crusher", "RDL", or "pec deck" even though the
// library row is named differently. Keyed by the database name; entries exist
// for both pre- and post-rename names so search keeps working while a naming
// migration is pending. Enriched from a strengthlevel.com audit of common
// alternate names.

const ALIASES: Record<string, string[]> = {
  // Big barbell lifts (strengthlevel's short names)
  "Squat": ["back squat", "barbell squat", "barbell back squat"],
  "Bench Press": ["barbell bench press", "flat bench", "bb bench", "bench"],
  "Deadlift": ["conventional deadlift", "barbell deadlift"],
  "Shoulder Press": ["overhead press", "ohp", "strict press", "barbell shoulder press", "standing barbell press"],
  "Military Press": ["strict overhead press", "standing military press"],
  "Bent Over Row": ["barbell row", "bb row", "bent-over row"],
  "Romanian Deadlift": ["rdl", "barbell romanian deadlift"],
  "Hex Bar Deadlift": ["trap bar deadlift", "hex deadlift"],
  "Close Grip Bench Press": ["close-grip bench press", "cgbp", "narrow grip bench"],
  "Hip Thrust": ["barbell hip thrust", "hip thruster"],
  "Front Squat": ["barbell front squat", "clean grip front squat"],
  "Sumo Deadlift": ["sumo dl", "wide stance deadlift"],
  "Good Morning": ["barbell good morning"],
  "Rack Pull": ["rack deadlift", "pin pull", "partial deadlift"],
  "Upright Row": ["barbell upright row"],
  "Pendlay Row": ["dead stop row"],
  "Barbell Shrug": ["shrug", "bb shrug"],
  "Preacher Curl": ["scott curl", "ez bar preacher curl"],
  "Snatch": ["squat snatch", "full snatch"],
  "Clean": ["squat clean", "full clean"],
  "Clean and Jerk": ["c&j", "clean & jerk"],
  "Push Press": ["barbell push press"],
  "Overhead Squat": ["ohs", "snatch grip overhead squat"],
  "Box Squat": ["squat to box", "barbell box squat"],
  "Pause Squat": ["paused squat", "bottom pause squat"],
  "Deficit Deadlift": ["deadlift from deficit", "elevated deadlift"],
  "Stiff-Leg Deadlift": ["sldl", "stiff leg deadlift", "straight leg deadlift"],
  "Floor Press": ["barbell floor press", "floor bench press"],
  "Power Snatch": ["powersnatch"],
  "Seal Row": ["bench pull", "prone bench row", "lying barbell row"],
  "Smith Machine Squat": ["smith squat", "smith machine back squat"],
  "Smith Machine Bench Press": ["smith bench press"],
  "Wrist Curl": ["forearm curl", "barbell wrist curl", "seated wrist curl"],
  "Reverse Wrist Curl": ["wrist extension", "overhand wrist curl"],
  "Belt Squat": ["hip belt squat", "machine belt squat"],

  // Hyphen and plural variants (the normalizer of last resort)
  "Pull Ups": ["pull-up", "pullup", "pull up", "overhand pull-up"],
  "Chin Ups": ["chin-up", "chinup", "chin up", "underhand pull-up"],
  "Push Ups": ["push-up", "pushup", "push up", "press-up"],
  "Sit Ups": ["sit-up", "situp", "sit up"],
  "Diamond Push Ups": ["diamond push-up", "triangle push up", "close hands push up"],
  "Neutral Grip Pull Ups": ["neutral-grip pull-up", "hammer grip pull up", "parallel grip pull up"],
  "Muscle Ups": ["muscle-up", "bar muscle up"],
  "One Arm Push Ups": ["one-arm push-up", "single arm push up"],
  "EZ Bar Curl": ["ez-bar curl", "ez curl", "cambered bar curl"],
  "T Bar Row": ["t-bar row", "landmine row", "lever row"],
  "Bodyweight Squat": ["air squat", "bw squat", "free squat"],
  "Dips": ["dip", "parallel bar dips", "chest dips", "triceps dips"],
  "Crunches": ["crunch", "ab crunch", "floor crunch"],
  "Pistol Squat": ["one legged squat", "single leg pistol", "one leg squat"],
  "Inverted Row": ["australian pull-up", "bodyweight row", "horizontal row"],
  "Incline Push-Up": ["hands elevated push up", "incline push up"],
  "Decline Push-Up": ["feet elevated push up", "decline push up"],
  "Hanging Knee Raise": ["knee raise", "hanging bent knee raise"],
  "Lying Leg Raise": ["floor leg raise", "supine leg raise"],
  "Hanging Leg Raise": ["hlr", "hanging straight leg raise"],
  "Back Extension": ["hyperextension", "45 degree back extension", "roman chair"],
  "Ab Wheel Rollout": ["ab rollout", "wheel rollout", "ab roller"],
  "Russian Twist": ["seated twist", "oblique twist"],
  "Bicycle Crunch": ["bicycle kicks", "alternating crunch", "cross-body crunch"],

  // Machines and cables, where slang rules
  "Machine Chest Fly": ["pec deck", "pec dec", "butterfly machine", "chest fly machine", "seated machine fly"],
  "Machine Reverse Fly": ["reverse pec deck", "rear delt machine", "reverse fly machine"],
  "Reverse Pec Deck": ["machine reverse fly", "rear delt machine"],
  "Cable Fly": ["cable crossover", "crossover", "standing cable fly", "cable chest fly"],
  "Cable Reverse Fly": ["cable rear delt fly", "reverse cable crossover"],
  "Tricep Pushdown": ["triceps pushdown", "cable pushdown", "straight bar pushdown"],
  "Rope Pushdown": ["tricep rope pushdown", "rope tricep pushdown", "triceps rope", "cable rope pushdown"],
  "Lying Tricep Extension": ["skull crusher", "skullcrusher", "lying triceps extension", "french press"],
  "Lying Dumbbell Tricep Extension": ["dumbbell skull crusher", "db skullcrusher", "lying db triceps extension"],
  "Overhead Triceps Extension": ["overhead tricep extension", "french press", "two-hand dumbbell extension"],
  "Cable Overhead Tricep Extension": ["overhead cable extension", "overhead rope extension", "cable french press"],
  "Seated Dip Machine": ["machine dip", "seated dips", "dip machine"],
  "Straight-Arm Pulldown": ["lat prayer", "straight arm pushdown", "stiff arm pulldown", "cable pullover"],
  "Seated Cable Row": ["cable row", "low row", "seated row"],
  "Lat Pulldown": ["wide grip lat pulldown", "pulldown", "cable pulldown"],
  "Close Grip Lat Pulldown": ["close-grip pulldown", "v-bar pulldown", "v bar pulldown"],
  "Face Pull": ["cable face pull", "rope face pull", "rear delt pull"],
  "Horizontal Leg Press": ["seated leg press", "machine leg press", "selectorized leg press"],
  "Sled Leg Press": ["45 degree leg press", "incline leg press", "sled press", "leg press"],
  "Hack Squat": ["machine hack squat", "sled hack squat"],
  "Chest Press": ["machine chest press", "seated chest press", "machine press"],
  "Machine Shoulder Press": ["seated machine shoulder press", "machine overhead press"],
  "Machine Lateral Raise": ["lateral raise machine", "seated machine side raise"],
  "Machine Preacher Curl": ["machine bicep curl", "machine curl", "seated machine curl", "preacher curl machine"],
  "Hip Adduction": ["adductor machine", "inner thigh machine", "hip adductor"],
  "Hip Abduction": ["abductor machine", "outer thigh machine", "hip abductor"],
  "Standing Calf Raise": ["machine calf raise", "calf raise", "calf raise machine"],
  "Machine Calf Raise": ["standing calf raise", "calf raise"],
  "Seated Calf Raise": ["seated calf machine", "seated soleus raise"],
  "Leg Press Calf Raise": ["calf press", "sled press calf raise", "sled calf press"],
  "Leg Extension": ["machine leg extension", "quad extension"],
  "Seated Leg Curl": ["seated hamstring curl"],
  "Lying Leg Curl": ["prone leg curl", "lying hamstring curl"],
  "Cable Curl": ["cable bicep curl", "low pulley curl", "standing cable curl"],
  "Cable Crunch": ["kneeling cable crunch", "rope crunch"],
  "Cable Pull-Through": ["pull through", "rope pull through", "glute pull through"],
  "Cable Lateral Raise": ["cable side raise", "low pulley lateral raise"],
  "Assisted Pull-Up": ["assisted pullup", "pull up machine", "pull-up machine"],

  // Dumbbell work
  "Dumbbell Lateral Raise": ["lateral raise", "side raise", "side lateral raise", "db lateral raise"],
  "Dumbbell Bench Press": ["db bench press", "db bench", "flat dumbbell press", "dumbbell chest press"],
  "Incline Dumbbell Bench Press": ["incline dumbbell press", "incline db press"],
  "Decline Dumbbell Press": ["decline db press", "decline dumbbell bench press"],
  "Dumbbell Fly": ["dumbbell flye", "flat dumbbell fly", "chest fly"],
  "Incline Dumbbell Fly": ["incline fly", "incline flye", "incline chest fly"],
  "Dumbbell Row": ["single arm row", "one arm row", "single-arm dumbbell row", "kroc row", "db row"],
  "Chest-Supported Row": ["incline dumbbell row", "prone dumbbell row", "chest supported dumbbell row"],
  "Dumbbell Bulgarian Split Squat": ["bulgarian split squat", "bss", "rfess", "rear foot elevated split squat"],
  "Barbell Bulgarian Split Squat": ["barbell rfess", "bb bulgarian split squat"],
  "Dumbbell Shoulder Press": ["db overhead press", "standing dumbbell press", "dumbbell overhead press"],
  "Seated Dumbbell Shoulder Press": ["seated dumbbell press", "seated db press"],
  "Dumbbell Curl": ["bicep curl", "db curl", "standing dumbbell curl", "alternating dumbbell curl"],
  "Seated Dumbbell Curl": ["seated curl", "seated bicep curl"],
  "Incline Dumbbell Curl": ["incline curl", "incline db curl"],
  "Hammer Curl": ["db hammer curl", "neutral grip curl"],
  "Concentration Curl": ["seated concentration curl", "dumbbell concentration curl"],
  "Dumbbell Romanian Deadlift": ["db rdl", "dumbbell rdl", "dumbbell stiff leg deadlift"],
  "Dumbbell Lunge": ["db lunge", "forward lunge", "dumbbell forward lunge"],
  "Walking Lunge": ["lunges"],
  "Front Raise": ["db front raise", "front delt raise", "dumbbell front raise"],
  "Rear Delt Fly": ["dumbbell reverse fly", "bent over reverse fly", "rear delt raise", "reverse flye"],
  "Triceps Kickback": ["kickback", "db kickback", "dumbbell tricep kickback"],
  "Dumbbell Pullover": ["db pullover", "lying dumbbell pullover"],
  "Dumbbell Shrug": ["db shrug"],
  "Goblet Squat": ["dumbbell goblet squat", "kb goblet squat"],
  "Arnold Press": ["seated arnold press", "rotational dumbbell press"],
  "Single-Leg Calf Raise": ["dumbbell calf raise", "db calf raise", "one leg calf raise"],
  "Kettlebell Swing": ["kb swing"],
  "Barbell Curl": ["standing barbell curl", "bb curl", "straight bar curl"],
};

/** Alternate search names for an exercise (empty when none are known). */
export function aliasesFor(name: string): string[] {
  return ALIASES[name] ?? [];
}
