-- 0016 - Training plans generated by the AI coach.
--
-- A plan is a weekly rotation of days, each holding an ordered list of
-- exercises with a set and rep prescription. The athlete's logged sets stay in
-- workout_sets exactly as before; a plan only says what to DO, never what was
-- done, so nothing here changes how history or analytics work.
--
-- Idempotent, and RLS-owned like every other user table.

create table if not exists public.training_plans (
  id              uuid primary key default uuid_generate_v4(),
  user_id         uuid not null references auth.users (id) on delete cascade,
  name            text not null,
  goal            text not null,                   -- hypertrophy | strength | both
  split           text not null,                   -- ppl | upper_lower | full_body | arnold | custom
  days_per_week   smallint not null check (days_per_week between 1 and 7),
  session_minutes smallint,
  equipment       text[] not null default '{}',    -- what they can actually train with
  avoid           text[] not null default '{}',    -- injuries, disliked movements
  mesocycle_weeks smallint not null default 5,     -- accumulation weeks plus the deload
  deload_week     smallint,                        -- 1-indexed week inside the mesocycle
  notes           text,
  active          boolean not null default true,
  started_on      date not null default current_date,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.plan_days (
  id        uuid primary key default uuid_generate_v4(),
  plan_id   uuid not null references public.training_plans (id) on delete cascade,
  day_index smallint not null,                     -- 0-based position in the weekly rotation
  name      text not null,                         -- "Push A"
  focus     text,                                  -- "chest, shoulders, triceps"
  unique (plan_id, day_index)
);

create table if not exists public.plan_exercises (
  id           uuid primary key default uuid_generate_v4(),
  plan_day_id  uuid not null references public.plan_days (id) on delete cascade,
  exercise_id  uuid not null references public.exercises (id),
  position     smallint not null,
  sets         smallint not null check (sets between 1 and 12),
  rep_low      smallint not null check (rep_low between 1 and 100),
  rep_high     smallint not null check (rep_high between 1 and 100),
  rpe_target   numeric(3, 1),
  rest_seconds smallint,
  role         text,                                -- primary | secondary | isolation
  note         text,
  check (rep_high >= rep_low),
  unique (plan_day_id, position)
);

create index if not exists training_plans_user_idx on public.training_plans (user_id);
-- One active plan per athlete, enforced rather than assumed.
create unique index if not exists training_plans_one_active
  on public.training_plans (user_id) where active;
create index if not exists plan_days_plan_idx on public.plan_days (plan_id);
create index if not exists plan_exercises_day_idx on public.plan_exercises (plan_day_id);

drop trigger if exists training_plans_set_updated_at on public.training_plans;
create trigger training_plans_set_updated_at
  before update on public.training_plans
  for each row execute function public.set_updated_at();

alter table public.training_plans enable row level security;
alter table public.plan_days enable row level security;
alter table public.plan_exercises enable row level security;

drop policy if exists "plans_own" on public.training_plans;
create policy "plans_own" on public.training_plans
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Days and exercises inherit ownership through their plan, so a user can only
-- reach rows that hang off a plan they own.
drop policy if exists "plan_days_own" on public.plan_days;
create policy "plan_days_own" on public.plan_days
  for all using (
    exists (select 1 from public.training_plans p
            where p.id = plan_days.plan_id and p.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.training_plans p
            where p.id = plan_days.plan_id and p.user_id = auth.uid())
  );

drop policy if exists "plan_exercises_own" on public.plan_exercises;
create policy "plan_exercises_own" on public.plan_exercises
  for all using (
    exists (select 1 from public.plan_days d
            join public.training_plans p on p.id = d.plan_id
            where d.id = plan_exercises.plan_day_id and p.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.plan_days d
            join public.training_plans p on p.id = d.plan_id
            where d.id = plan_exercises.plan_day_id and p.user_id = auth.uid())
  );
